version: 2
jobs:
  prepare_ros_workspace:
    docker:
      - image: kshitijkabeer/ros-sim:1.0.2
    steps:
      - run: |
          cd ../
          mkdir -p test_ws/src/$CIRCLE_PROJECT_REPONAME
          yes | apt-get install libcgal-dev || true
          apt-get update -y
          apt-get install ros-melodic-xacro
          apt install libyaml-cpp-dev
          apt-get install -y python-pip
          python -m pip install cpplint
      - checkout:
          path: /root/test_ws/src/$CIRCLE_PROJECT_REPONAME
      - run: |
          cd ../test_ws/
          wstool init src src/$CIRCLE_PROJECT_REPONAME/install/install_https.rosinstall
          wstool update -t src
      - persist_to_workspace:
          root: /root
          paths: test_ws/*

  catkin_build:
    docker:
      - image: kshitijkabeer/ros-sim:1.0.2
    steps:
      - attach_workspace:
          at: /root
      - run: |
          cd ../test_ws/
          source /opt/ros/melodic/setup.bash
          . ./src/iarc_simulation_tools/test_script.sh
          
workflows:
  version: 2
  build_test:
    jobs:
      - prepare_ros_workspace
      - catkin_build:
          requires:
            - prepare_ros_workspace